---
title: "Contact"
format: html
---

# 📞 Let's connect

Thank you for visiting my portfolio. I welcome opportunities to collaborate, network, and contribute to impactful work in finance, business analytics, and strategic decision-making.

Whether you are exploring potential roles, seeking analytical support, or interested in discussing research and industry trends, I am always open to meaningful professional convers

---

## 📧 Email  
priya.pathak@live.com  

## 🔗 LinkedIn  
🌐 [Priya Pathak](https://www.linkedin.com/in/priya-pathak-162b16ab?utm_source=share_via&utm_content=profile&utm_medium=member_ios)  

---

## 💼 Open To Roles In:
- Financial planning & analysis (FP&A)
- Business and investment analytics
- Corporate finance roles
- Data-driven strategy and performance evaluation
- Graduate research and collaborative academic projects

---

## 🤝 Professional Interests
I enjoy engaging in discussions related to:
Investment appraisal and financial decision-making
Emerging trends in FinTech and data analytics
Sustainable financial strategy and value creation
Business transformation supported by quantitative insights

---

## 📍 Location  
Vancouver, BC (Open to remote/hybrid/on-site)

---

## 🕒 Response Time  
Typically responds within 24–48 hours.

